sudo: required

language: node_js
node_js:
  - node

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - npm install -g bats

matrix:
  include:
    - name: "debian"
      env: MAKE_TARGET=test-debian
    - name: "slim"
      env: MAKE_TARGET=test-slim
    - name: "alpine"
      env: MAKE_TARGET=test-alpine
script:
  - make $MAKE_TARGET

deploy:

  - provider: script
    # script: curl --request POST --header Content-Type:application/json --data '{"build":true}' --url ${DOCKER_CLOUD_TRIGGER_URL}
    script: ./publish.sh latest
    on:
      branch: master

  - provider: script
    script: ./publish.sh $TRAVIS_TAG
    on:
      tags: true
      condition: $TRAVIS_TAG =~ ^v.*$

  - provider: script
    script: ./publish.sh multi-image-dist
    on:
      branch: multi-image-dist
